### ISSUE TITLE
tootctl command hangs/freezes

### ISSUE THREAD

**Issue by jbold** [widdix/mastodon-on-aws#11]
I'm able to successfully open a shell to the webservice task - however issuing the tootctl command freezes/hangs. I have to ctl+c to interrupt. No errors are thrown.

`root@ip-10-0-4-35:/opt/mastodon# RAILS_ENV=production bin/tootctl help`

**Comment by schuettc** [comment]
Did you use the latest build with the increased memory size on the webserver task?  That helped me.  Although I was getting an error.

**Comment by jbold** [comment]
that's a good question - i'm unable to edit/view any of the config files...no vi/vim/nano editor...tried installing, but couldn't get vim working. is there another way to view/edit files?

**Comment by schuettc** [comment]
Most of the config is generated in the task definition of the ECS Task.  You can see it in the JSON there.

**Comment by jbold** [comment]
got it, thanks!
