### ISSUE TITLE
Alb cannot be created in us-west-1a

### ISSUE THREAD

**Issue by pegli** [widdix/mastodon-on-aws#13]
I'll admit that this sounds very unlikely, but CloudFormation is reporting that an Application Load Balancer isn't available in us-west-1a:

`The following Availability Zones us-west-1a cannot be associated with a load balancer. Please try a different Availability Zone. (Service: AmazonElasticLoadBalancing; Status Code: 400; Error Code: ValidationError; Request ID: 93e9babc-7135-4d02-b79a-8cfbc27642b2; Proxy: null)`

When I create a target group and load balancer by hand, I get the same error:

`The following Availability Zones us-west-1a cannot be associated with a load balancer. Please try a different Availability Zone.`

I'm able to create an ALB if I remove us-west-1a from the list of AZs.  Any guidance on how to set up the ALB and target groups manually?

**Comment by andreaswittig** [comment]
Hm, I've never heard about that. Let me investigate a little bit.

**Comment by andreaswittig** [comment]
@pegli As a workaround, have you thought about using another region?

**Comment by pegli** [comment]
Yes, though I'd like to get it to work in us-west-1 because I'm standing up an instance for my local community in California.  Not that latency is going to be a big deal, of course... :)

**Comment by michaelwittig** [comment]
Fixing this is not easy. The way we select the AZs during VPC creation is via CloudFormation's [Fn::GetAZs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getavailabilityzones.html).

There is no way to configure `Fn::GetAZs` to only return AZs with certain features. E.g., we would need AZs that support ALBs as well as t4g RDS instances.

**Comment by pegli** [comment]
On 2/16, I was able to successfully deploy the 0.10.0 templates in us-west-1.  My VPC subnets are all in 1a and 1c this time around.
