### ISSUE TITLE
"Resource of type 'AWS::SES::EmailIdentity' with identifier 'xxxxxxxxxxxx.social' already exists." 

### ISSUE THREAD

**Issue by surfd4wg** [widdix/mastodon-on-aws#27]
Getting an error message when I try to run the CF stack.

2022-12-23 12:54:32 UTC-0700	EmailIdentity	CREATE_FAILED	Resource handler returned message: "Resource of type 'AWS::SES::EmailIdentity' with identifier 'xxxxxxxxxxxx.social' already exists." (RequestToken: b4171337-8e59-b080-5f57-9b5605e10fce, HandlerErrorCode: AlreadyExists)

**Comment by andreaswittig** [comment]
Thanks for reporting this. Did you launch the CloudFormation stack `mastodon-on-aws` multiple times? Or did you manually configure SES for that AWS account before?

**Comment by surfd4wg** [comment]
Sorry, I thought I had email notifications turned on. So this happened the first time I ran the CF stack.  I think I manually configured SES before running the CF Stack.

**Comment by andreaswittig** [comment]
You could either remove the `AWS::SES::EmailIdentity` from the template or remove the SES email identity that you configured before via the AWS Management Console.

**Comment by surfd4wg** [comment]
Removed the SES identity that I configured before. Stack worked.
