### ISSUE TITLE
Stuck on creating certificate for my subdomain

### ISSUE THREAD

**Issue by JohnCido** [widdix/mastodon-on-aws#28]
I'm using a subdomain social.xxx.xxx for my site, but the certificate stuck on verification. I saw the section about Route 53 in the README, but I can't find a way to create two NS records for my hosted zone. And I did not buy the domain on AWS, should I go to my original domain merchant to add four more NS records?

**Comment by andreaswittig** [comment]
By creating the CloudFormation stack, you are creating a Route53 hosted zone in your AWS account. The hosted zone is associated with four nameservers. You need to create a NS record `social.xxx.xxx` pointing to the AWS nameservers wherever you are hosting your domain.

**Comment by GregCKrause** [comment]
It is also worth noting that, in addition to an NS record, you will need to ensure that your registered domain is pointing to the nameservers for the hosted zone.

[Add or change name servers or glue records for a domain](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/domain-name-servers-glue-records.html#domain-name-servers-glue-records-adding-changing-procedure).

**Comment by scrappydog** [comment]
This is a setup issue that could use better documentation: Specifically certificate creation hangs and blocks everything until you have the correct NS records setup pointing to the correct route 53 servers for the new zone.

**Comment by andreaswittig** [comment]
@scrappydog Do you have any recommendation on how to improve the docs?

**Comment by JohnCido** [comment]
Oh my god, I think I found the part that confused me most, if the subdomain field is left blank, you can't change the type to NS:
<img width="842" alt="image" src="https://user-images.githubusercontent.com/7105485/210573748-48996536-9293-43ec-abd5-41e02621a8e5.png">
I usually choose the type first when creating new record, never thought of another way around.

I just created a new stack and I'll see if there's any problem this time.
