### ISSUE TITLE
Trying to enable admin through tootctl - SessionManagerPlugin is not found

### ISSUE THREAD

**Issue by surfd4wg** [widdix/mastodon-on-aws#30]
aws ecs execute-command --cluster "redacted" --container app --command /bin/bash --interactive --task "redacted"

SessionManagerPlugin is not found. Please refer to SessionManager Documentation here: 

http://docs.aws.amazon.com/console/systems-manager/session-manager-plugin-not-found

**Comment by andreaswittig** [comment]
@surfd4wg Did you follow the link and install the session manager plugin?

**Comment by surfd4wg** [comment]
Install it where, in the Mastodon Containers?

**Comment by andreaswittig** [comment]
No, you need to install the session manager plugin for the AWS CLI running on your local machine.

**Comment by surfd4wg** [comment]
I'm smarter than I look. Really.
