### ISSUE TITLE
Would be great if we could  use CloudFront to serve static images instead of S3 public access

### ISSUE THREAD

**Issue by natetallman** [widdix/mastodon-on-aws#32]
Is anyone working on that currently? I'd like to take a stab at it, although I'm new to mastodon. I don't want to duplicate efforts if someone else has that going.

**Comment by andreaswittig** [comment]
Working on that right now.

**Comment by andreaswittig** [comment]
@natetallman Just released v0.10.0 which adds CloudFront to distribute user uploads stored on S3.

**Comment by andreaswittig** [comment]
Sorry, the build for `v0.10.0` failed. Please use `v0.10.1` instead.

**Comment by maooson** [comment]
@andreaswittig Thank you, you did an excellent job. I successfully deployed [my Mastodon instance](https://social.aoq.me) using your solution.
