### ISSUE TITLE
Development section instructions seem to skip necessary packages

### ISSUE THREAD

**Issue by austinmw** [widdix/mastodon-on-aws#45]
I don't see a `vpc-plain` in `node_modules/@cfn-modules/` when I run `npm install`. However `node_modules/@cfn-modules/vpc/module.yml` references it:
`TemplateURL: './node_modules/@cfn-modules/vpc-plain/module.yml'`

<img width="1337" alt="image" src="https://github.com/widdix/mastodon-on-aws/assets/12224358/1e82d448-2ff2-4e91-a933-1de2c938ef61">

**Comment by andreaswittig** [comment]
I've fixed the issue.
