### ISSUE TITLE
Document what permissions are needed?

### ISSUE THREAD

**Issue by denishaskin** [widdix/mastodon-on-aws#7]
I'm setting up an IAM user to build my instance with, but I'm not sure what permissions it needs.  I'll probably just throw a lot of FullAccess policies at it until it works.

But if the documentation could be updated with the minimal set of permissions, that would be great.  I'll do it if I get a chance, once I get this set up.

**Comment by michaelwittig** [comment]
Hi @denishaskin 
Are you asking for the permissions that are needed to deploy the CloudFormation stack? If so, I can not suggest a good approach of tackling this task. CloudFormation does not publish the needed permissions for most of it's resource types. Even with trial and error you will likely not succeed. CloudFormation can create, update and delete resources. Testing all those situations for each and every resource is challenging (if not impossible).
