### ISSUE TITLE
Post-Deploy Steps

### ISSUE THREAD

**Issue by schuettc** [widdix/mastodon-on-aws#9]
Looks like everything deployed correctly.  I can get to the task via CLI.  But no response from the actual site itself.  R53 appears to be resolving correctly to the ALB.  Is there something that needs to be done on the server itself to start it?

**Comment by andreaswittig** [comment]
What's the output of `curl -v https://<INSERT_YOUR_DOMAIN>`?

**Comment by schuettc** [comment]
502 Bad Gateway

curl -v https://social.subaud.io
*   Trying 107.21.221.36:443...
* Connected to social.subaud.io (107.21.221.36) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=social.subaud.io
*  start date: Nov 21 00:00:00 2022 GMT
*  expire date: Dec 20 23:59:59 2023 GMT
*  subjectAltName: host "social.subaud.io" matched cert's "social.subaud.io"
*  issuer: C=US; O=Amazon; CN=Amazon RSA 2048 M01
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* h2h3 [:method: GET]
* h2h3 [:path: /]
* h2h3 [:scheme: https]
* h2h3 [:authority: social.subaud.io]
* h2h3 [user-agent: curl/7.84.0]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x14d00a800)
> GET / HTTP/2
> Host: social.subaud.io
> user-agent: curl/7.84.0
> accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 502
< server: awselb/2.0
< date: Mon, 21 Nov 2022 19:28:09 GMT
< content-type: text/html
< content-length: 122
<
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>
* Connection #0 to host social.subaud.io left intact

**Comment by andreaswittig** [comment]
Could you please check the CloudWatch Log Group named `cloudonaut-mastodon-WebService-` for error messages?

**Comment by schuettc** [comment]
Just restarted the task and it seems to be working now.  Was fairly sporadic, but restarting task seemed to help.  Looks stable now.  Maybe a timing issue with deployment?  Added R53 domain half way through deploy.

**Comment by schuettc** [comment]
BTW, repeatedly got "Killed" in response to an attempt to modify a user from CLI.  Upgraded task to:
Task memory (MiB) 2048
Task CPU (unit) 1024

It seems to have resolved that issue.

**Comment by andreaswittig** [comment]
Thanks, I'm running into the same issue right now. ;)
